# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.






# Site settings
title: TF铁匠铺
email: suyun1331@163.com
SEOTitle: wykhan 博客 | wykhan
header-img: img/home-bg.jpg
description: "数据科学家的尝试"
keyword: "tensorflow,NLP,data mini"
url: "https://wykhan.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     wykhan
github_username:    wykhan
kaggle_username:    wykhan
# linkedin_username:  firstname-lastname-idxxxx



description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

layouts_dir: ./_layouts



# Duoshuo settings
duoshuo_username: WykhanBlog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "怀着谦卑之心前行，<br>通过认知，获得力量"
sidebar-avatar: /img/avatar-cat.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



